fix(preflights): template secrets for local preflights as well
GitGuardian/ggtools pull request #11
Opened 2024-05-31 09:30 UTC by ggrosseveurgg

fix(preflights): template secrets for local preflights as well

2024-06-03 08:49 UTC, ggguardian requested changes

2024-06-03 08:49 UTC, ggguardian commented on helm-preflights/preflights.sh
> +    kubectl apply -f $script_dir/local_secrets.yaml &>/dev/null
You need to specify the namespace here since it's not specified in the manifest (`local_secrets.yaml`):

```suggestion
    kubectl -n $NAMESPACE apply -f $script_dir/local_secrets.yaml &>/dev/null
```

Also,you need to check that there is no error running this command otherwise the script will continue

2024-06-03 08:49 UTC, ggguardian commented on helm-preflights/preflights.sh
> +    GLOBAL_RC=1
Why don't you just exit with an error code here? 
it would avoid useless checks using `PULL_SECRETS_OK`?

2024-06-03 09:12 UTC, ggrosseveurgg commented on helm-preflights/preflights.sh
> +    GLOBAL_RC=1
We would miss the fact that user played preflights in results/telemetry (we won't write anything to the gitguardian-preflights-results secret at the end). Not worth ?

2024-06-03 09:30 UTC, ggguardian commented on helm-preflights/preflights.sh
> +    GLOBAL_RC=1
Ok I see, but my feeling here is that it is not very easy to read/maintain, what about using the `trap` bash feature instead to run commands at the end of the script?

2024-06-03 15:53 UTC, ggrosseveurgg commented on helm-preflights/preflights.sh
> +    GLOBAL_RC=1
I rewrote part of the code to try to make it clearer

2024-06-04 05:23 UTC, ggguardian reviewed
LGTM 👍

2024-06-04 05:23 UTC, ggguardian commented on helm-preflights/preflights.sh
>        exit 1
It can be removed now.

2024-06-04 07:40 UTC, merged